services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: realtimechat-backend
    expose:
      - "8081"
      - "8080"
    networks:
      - appnet
    environment: # Use host's MySQL from inside the container
          SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/RealTimeChatApp
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: "Virendra@123"
          SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
          SERVER_PORT: "8081"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend
    container_name: realtimechat-frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
      - "5173:80"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
version: "3.9"


